name: Deploy Azure Alert Rules

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy-alerts:
    runs-on: windows-latest  # Use Windows runner to support PowerShell scripts

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Azure PowerShell Module
        run: |
          Install-Module -Name Az -Force -Scope CurrentUser -AllowClobber
          Import-Module Az
        shell: pwsh

      - name: Check Installed PowerShell Modules
        run: |
          Get-Module -ListAvailable Az*
        shell: pwsh

      - name: Authenticate to Azure
        run: |
          Connect-AzAccount -Identity
        shell: pwsh

      - name: Execute Customer-Specific Alert Deployment
        run: |
          pwsh -File ./GitHubLab/Customers/${{ github.event.inputs.customer }}/Cus${{ github.event.inputs.customer }}-Alerts-Main.ps1
        shell: pwsh

      - name: Post Checkout Repository
        run: echo "Repository checkout completed."

      - name: Complete job
        run: echo "Azure alert deployment workflow finished."
